quiz/urls.py
from django.urls import include, path
from . import views

app_name = "quiz"
urlpatterns = [
    path("<int:quiz_id>/start", views.start, name="start"),
    path("<int:quiz_id>/questions", views.question, name="question"),
    path("postAnswers", views.post_answers, name="postAnswers"),
    path("<int:quiz_id>/results", views.results, name="results"),
]

quiz/models.py
from django.db import models


class Quiz(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    topics = models.CharField(max_length=200, blank=True, default="")
    def __str__(self):
        return self.title

class Question(models.Model):
    SINGLE_ANS = "SIN"
    ONE_OR_MORE_ANS = "OOM"
    QUESTION_TYPES = {
        SINGLE_ANS: "Single correct answer",
        ONE_OR_MORE_ANS: "One or more correct answers",
    }
    quiz = models.ForeignKey(Quiz, null=True, on_delete=models.SET_NULL)
    text = models.CharField(max_length=200)
    question_type = models.CharField(max_length=3, choices=QUESTION_TYPES)
    def __str__(self):
        return self.text

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField()
    def __str__(self):
        return self.text

quiz/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.urls import reverse
import json

from .models import Quiz, Question, Answer
from users.models import Profile

# auxiliary functions
def format_answers(answers_data):
    # group answers by question id
    formatted_answers = {}
    for entry in answers_data:
        question_id = entry.split("-")[0]
        if question_id not in formatted_answers.keys():
            formatted_answers[question_id] = [] 
        formatted_answers[question_id].append(answers_data[entry])
    return formatted_answers

def calculate_score(results_dict):
    score = 0
    for question_id in results_dict:
        #TODO decide on scoring system for different types of questions
        answer_ids = results_dict[question_id]
        question = get_object_or_404(Question, pk=int(question_id))
        if question.question_type == "SIN":
            # award a flat 2 marks if user gave the question's only correct answer
            answer = get_object_or_404(Answer, pk=int(answer_ids[0]))
            if answer.is_correct == True:
                score += 2
        elif question.question_type == "OOM":
            # award marks based on proportion of correct answers
            correct_answers = 0
            for answer_id in answer_ids:
                answer = get_object_or_404(Answer, pk=int(answer_id))
                if answer.is_correct:
                    correct_answers += 1
            if correct_answers / question.answer_set.filter(is_correct=True).count() == 1:
                score += 3
            elif correct_answers / question.answer_set.filter(is_correct=True).count() > 0.65:
                score += 1
    return score

@login_required
def start(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    return render(request, "quiz/start.html", {"quiz": quiz})

@login_required
def question(request, quiz_id):
    # question_index starts at 1 for url readability
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    return render(request, "quiz/question.html", {"quiz":quiz})

def post_answers(request):
    # dedicated backend view to process quiz rewards - prevents refreshing and resubmitting for rewards
    if request.method == "POST":
        # process POST request input
        post_dict = json.load(request)
        results_dict = format_answers(post_dict)
        score = calculate_score(results_dict)
        # save points and coins to database
        points = score * 100
        marker = request.user.id
        profile = Profile.objects.get(user=marker)
        profile.points_amount += points
        profile.coins_amount += score
        profile.save()
        return HttpResponse("success")

@login_required
def results(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    if request.method == "POST":
        # process POST request input
        request_as_dict = request.POST.dict()
        del request_as_dict["csrfmiddlewaretoken"]
        results_dict = format_answers(request_as_dict)
        answer_id_list = []
        for answer_list in results_dict.values():
            for answer_id in answer_list:
                answer_id_list.append(int(answer_id))        
        score = calculate_score(results_dict)
        context = {
                    "quiz": quiz,
                    "user_answers": answer_id_list,
                    "points": score * 100,
                    "coins": score,
                }
        return render(request, "quiz/results.html", context)

quiz/templates/quiz/question.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'quiz/question.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Outfit">
  </head>
  <header>
    <div class="topnav">
        <a href="{% url 'home' %}" class="nav-item nav-link" >Home</a>
        <a href="{% url 'profile' %}" class="nav-item nav-link" >Profile</a>
        <a href="{% url 'game_map' %}" class="nav-item nav-link">Activites</a>
        {% if request.user.is_staff == True %}
            <a href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <!--<a class="nav-item nav-link" href="javascript:$('#frm_logout').submit();">Log Out</a>-->
            <button type="submit">Log Out</button>
        </form>
    </div>
  </header>
  <body>
    <div class="centre">
      <form id="question-set" action="{% url 'quiz:results' quiz.id %}" method="post">
        {% csrf_token %}
        {% for question in quiz.question_set.all %}
          <fieldset>
            <legend><h1>{{ question.text }}</h1></legend>
            {% if question.question_type == "SIN" %}
              <!-- Radio button answers are posted in the format "question.id=answer.id" -->
              {% for answer in question.answer_set.all %}
                <div class="answer-{{ forloop.counter }}">
                  <label class="container1">
                    <input type="radio" name="{{ answer.question.id }}" value="{{ answer.id }}"/>
                    <span class="checkmark1"></span>
                    <label for="{{ answer.question.id }}">{{ answer.text }}</label><br>
                  </label>
                </div>
              {% endfor %}
            {% else %}
              <!-- Checkbox answers are posted in the format "question.id-[answer index]=answer.id" -->
              {% for answer in question.answer_set.all %}
                <div class="answer-{{ forloop.counter }}">
                  <label class="container2">
                    <input type="checkbox" name="{{ answer.question.id }}-{{ forloop.counter }}" value="{{ answer.id }}"/>
                    <span class="checkmark2"></span>
                    <label for="{{ answer.question.id }}-{{ forloop.counter }}">{{ answer.text }}</label><br>
                  </label>
                </div>
              {% endfor %}
            {% endif %}
          </fieldset>
        {% endfor %}
        <input type="submit" onclick="postAnswers()" value="Results &rarr;"/>
      </form>
      <!-- <iframe name='formresponse' style="visibility: hidden; width:0; height:0;"></frame> -->
    </div>
  </body>
  <script>
    function getCookie(name) {
        // function provided by Django docs
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
            const cookies = document.cookie.split(";");
            for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + "=")) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function postAnswers() {
        // retrieve all selected answers from form
        console.log("entered post block")
        answers_data = {};
        answers = document.querySelectorAll("#question-set :checked");
        answers.forEach(answer => {
            answers_data[answer.name] = answer.value;
        });
        fetch("{% url 'quiz:postAnswers' %}", {
              method: "POST",
                credentials: "same-origin",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                    "X-CSRFToken": getCookie("csrftoken"),
                },
                body: JSON.stringify(answers_data),
          });
    }
  </script>
</html>

quiz/templates/quiz/questions.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'quiz/questions.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Outfit">
  </head>
  <body>
    <form id="question-set" action="{% url 'quiz:results' quiz.id %}" method="post">
      {% csrf_token %}
      {% for question in quiz.question_set.all %}
     <!--
        {% if forloop.first %}
          <div class="question-panel" style="visibility: visible;">
        {% else %}
          <div class="question-panel" style="visibility: hidden;">
        {% endif %}
          --> 
          <fieldset>
            <legend><h1>{{ question.text }}</h1></legend>
            {% if question.question_type == "SIN" %}
              <!-- Radio button answers are posted in the format "question.id=answer.id" -->
              {% for answer in question.answer_set.all %}
                <div class="answer-{{ forloop.counter }}">
                  <label class="container1">
                    <input type="radio" name="{{ answer.question.id }}" value="{{ answer.id }}"/>
                    <span class="checkmark1"></span>
                    <label for="{{ answer.question.id }}">{{ answer.text }}</label><br>
                  </label>
                </div>
              {% endfor %}
            {% else %}
              <!-- Checkbox answers are posted in the format "question.id-[answer index]=answer.id" -->
              {% for answer in question.answer_set.all %}
                <div class="answer-{{ forloop.counter }}">
                  <label class="container2">
                    <input type="checkbox" name="{{ answer.question.id }}-{{ forloop.counter }}" value="{{ answer.id }}"/>
                    <span class="checkmark2"></span>
                    <label for="{{ answer.question.id }}-{{ forloop.counter }}">{{ answer.text }}</label><br>
                  </label>
                </div>
                {% endfor %}
            {% endif %}
          </fieldset>
          {% if forloop.last %}
            <input type="submit" value="Results &rarr;"/>
          {% endif %}
        </div>
      {% endfor %}
    </form>
    <!-- Only display next button if there is more than one question -->
    {% if quiz.question_set.all|length > 1 %}
      <button id="next-q-button" onclick="nextQuestion();">Next &rarr;</button>
    {% endif %}
  </body>
  <script src="{% static 'quiz/questions.js' %}"></script>
</html>

quiz/templates/quiz/results.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'quiz/results.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 640px)" href="{% static 'quiz/results_mobile.css' %}" />
    <link rel="stylesheet" media="screen and (min-width:641px)" href="{% static 'quiz/results.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Outfit">
  </head>
  <header>
    <div class="topnav">
        <a href="{% url 'home' %}" class="nav-item nav-link" >Home</a>
        <a href="{% url 'profile' %}" class="nav-item nav-link" >Profile</a>
        <a href="{% url 'game_map' %}" class="nav-item nav-link">Activites</a>
        {% if request.user.is_staff == True %}
            <a href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <!--<a class="nav-item nav-link" href="javascript:$('#frm_logout').submit();">Log Out</a>-->
            <button type="submit">Log Out</button>
        </form>
    </div>
  </header>
  </header>
  <body>
    <div class="centre">
        <fieldset>
            <legend><h11>{{ quiz.title }}</h11></legend>
            {% for question in quiz.question_set.all %}
            <div class="question-block">
                <h2>{{forloop.counter}}. {{ question.text }}</h2>
                <ul>
                    {% for answer in question.answer_set.all %}
                        {% if answer.id in user_answers %}
                            <span class="user-selected">
                        {% else %}
                        <span class="user-did-not-select">
                        {% endif %}
                            {% if answer.is_correct %}
                                <li class="correct">
                            {% else %}
                                <li class="incorrect">
                            {% endif %}
                                {{ answer.text }}
                            </li>
                        </span>
                    {% endfor %}
                </ul>
        {% endfor %}
        </fieldset>
        <h2>You gained:</h2>
        <ul>
            <li>{{ points }} points!</li>
            <li>{{ coins }} sustainabills!</li>
        </ul>
        <button class="home" onclick="window.location.href='{% url "home" %}'">Return to home page</button>
    </div>
  </body>
</html>

quiz/templates/quiz/start.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'quiz/start.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 640px)" href="{% static 'quiz/start_mobile.css' %}" />
    <link rel="stylesheet" media="screen and (min-width:641px)" href="{% static 'quiz/start.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Outfit">
  </head>
  <header>
    <div class="topnav">
        <a href="{% url 'home' %}" class="nav-item nav-link" >Home</a>
        <a href="{% url 'profile' %}" class="nav-item nav-link" >Profile</a>
        <a href="{% url 'game_map' %}" class="nav-item nav-link">Activites</a>
        {% if request.user.is_staff == True %}
          <a href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <!--<a class="nav-item nav-link" href="javascript:$('#frm_logout').submit();">Log Out</a>-->
            <button class="log_out" type="submit">Log Out</button>
        </form>
    </div>
  </header>
  <body>
    <div class="centre">
      <fieldset>
        <legend><h11 class="title">{{ quiz.title }}</h11></legend>     
        <!-- COULD HAVE topic tags system with assigned colours -->
        {% if quiz.topics %}
          <p>Topics: {{ quiz.topics }}</p>
        {% endif %}        
        <h3>This quiz has {{ quiz.question_set.count }} question(s)</h3>
      </fieldset>
      <!-- Button redirects to first question in the quiz -->
      <button class="button" onclick="window.location.href='{% url 'quiz:question' quiz.id %}';">Start &rarr;</button>
    </div>
  </body>
</html>